config/routes.rb
Rails.application.routes.draw do
	root 'statics_pages#home'

	resources :gossips


	# ressources :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	validates :name, uniqueness: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user, required: false
	has_many :tags

	validates :title, presence: true
	validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossip
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city, required: false
	has_many :gossips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def index
		@user_tab = User.all
	  	@city_tab = City.all
	  	@gossip_tab = Gossip.all
	end


  def create
  	puts "-"*50
  	puts params

  	mon_gossip = Gossip.new(title: params[:title], content: params[:content], anonymous_gossiper: params[:author])
  	if mon_gossip.save
  		puts
  		puts mon_gossip.id
  		redirect_to	 gossip_path(mon_gossip.id)
  	else
  		redirect_to	 gossips_path
  	end
  end

  def show
  	@id = params[:id]
  	@title = Gossip.find(@id).title
  	@content = Gossip.find(@id).content
  	@anonymous_author = Gossip.find(@id).anonymous_gossiper
  end

  def edit
  	@gossip = Gossip.find(params[:id])
  	puts @gossip.id
  end

  def update
  	@id = params[:id]
  	@gossip = Gossip.find(@id)

  	gossip_param = params.require(:gossip).permit(:title, :content, :anonymous_gossiper)
  	@gossip.update(gossip_param)
  	
	redirect_to gossip_path
  end

  def destroy
  	@gossip = Gossip.find(params[:id])
  	@gossip.destroy
  	redirect_to root_path
  end

end

app/controllers/statics_pages_controller.rb
class StaticsPagesController < ApplicationController
  def home
  	@user_tab = User.all
  	@city_tab = City.all
  	@gossip_tab = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/statics_pages_helper.rb
module StaticsPagesHelper
end

app/views/gossips/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>EDIT GOSSIP</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>
	<header>
      <ul class="nav nav-pills nav-fill">
        <li class="nav-item"> <a class="nav-link" href= <%=root_path %> >Index des gossips</a> </li>
        <li class="nav-item"> <a class="nav-link" href= <%=gossips_path %> >Nouveau Gossip</a> </li>
      </ul>
    </header>



    <div class="center jumbotron">
    	<h1>Editons tout ca</h1>
	
    	<%= form_for @gossip do |f| %>
	    	<div class="form-group">
				<label>Anonymous Gossiper</label>
	    		<%= f.text_field :anonymous_gossiper, class: 'form-control' %>				
			</div>
			<div class="form-group">
				<label>Title</label>
	    		<%= f.text_field :title, class: 'form-control' %>				
			</div>
			<div class="form-group">
				<label>Content</label>
	    		<%= f.text_field :content, class: 'form-control' %>				
			</div>
			<div>
				<button type="submit" class="btn btn-primary" >Modifier le Gossip</button>
			</div>
    	<% end %>

	</div>

</body>
</html>

app/views/gossips/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>New Gossip</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>
	<header>
      <ul class="nav nav-pills nav-fill">

        <li class="nav-item"> <a class="nav-link" href= <%=root_path %> >Index des gossips</a> </li>
        <li class="nav-item"> <a class="nav-link active" href= <%=gossips_path %> >Nouveau Gossip</a> </li>
      </ul>
    </header>






	<div class="center jumbotron">
		<h1>nom_fichier: INDEX</h1>
		<h1>MAIS EN VRAI C'EST LE NEW GOSSIP</h1>
		<h3>Aller balance nous les potins :</h3>

		<form method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<div class="form-group">
			    <label>Anonymous Gossiper</label>
			    <input name="author" type="text" class="form-control" placeholder="Enter your name">
			</div>

		  <div class="form-group">
		    <label>Title</label>
		    <input name="title" type="text" class="form-control" placeholder="Enter Title">
		    <small class="form-text text-muted">Ecris un titre qui donne envie d'aller lire le Gossip ;)</small>
		  </div>

		  <div class="form-group">
		    <label>Content</label>
		    <input name="content" type="text" class="form-control" placeholder="Enter Content">
		  </div>

		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>

	</div>



</body>
</html>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SHOW</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>
	<header>
      <ul class="nav nav-pills nav-fill">
        <li class="nav-item"> <a class="nav-link" href= <%=root_path %> >Index des gossips</a> </li>
        <li class="nav-item"> <a class="nav-link" href= <%=gossips_path %> >Nouveau Gossip</a> </li>
      </ul>
    </header>


    <div class="center jumbotron">
	  <h1>Gossip N°<%= @id %> !</h1>
	  <% if @anonymous_author %>
	  	<h2> <%= @anonymous_author %> </h2>
	  <% else %>
	  	<h2> Auteur Anonyme</h2>
	  <% end %>

	  <h3> <%= @title %> </h3>
	  <p> <%= @content %> </p>

	   <%= link_to "Editer ce Gossip", edit_gossip_path, class: "btn btn-lg btn-primary" %>
	   <%= link_to "Revenir à l'Index", root_path, class: "btn btn-lg btn-primary" %>



	</div>


	

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statics_pages/_header.html.erb
<header>
	<ul class="nav nav-pills nav-fill">
	  <li class="nav-item">
	    <a class="nav-link active" href="#">Accueil</a>
	  </li>

	  <li class="nav-item">
	    <a class="nav-link" href="#">Index des gossips</a>
	  </li>
	  
	  <li class="nav-item">
	    <a class="nav-link" href="#">Nouveau Gossip</a>
	  </li>
	</ul>
</header>

app/views/statics_pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>HOME</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
</head>
<body>
	 <header>
      <ul class="nav nav-pills nav-fill">

        <li class="nav-item"> <a class="nav-link active" href= <%=root_path %> >Index des gossips</a> </li>
        <li class="nav-item"> <a class="nav-link" href= <%=gossips_path %> >Nouveau Gossip</a> </li>
      </ul>
    </header>






	<div class="center jumbotron">
	  <h1>Bienvenue !</h1>
	  <h3> Ici, tu peux retrouver de bon Gossip 🎓 </h3>
	  <%= link_to "Nouveau Gossip", gossips_path, class: "btn btn-lg btn-primary" %>
	  <!-- <%= link_to "Voir les Gossip !", nil, class: "btn btn-lg btn-primary" %> -->
	</div>



	<h3>Voir TOUS les Gossip :</h3>
	<ul>
		<% @gossip_tab.each do |gossip| %>
			<li> <strong> <%= gossip.title+ ": "%></strong> </li>
			<p> <%= gossip.content %>   <a href="<%= gossip_path(gossip.id) %>" class="btn btn-primary">Voir Gossip Info</a> <a href="<%= gossip_path(gossip.id) %>" class="btn btn-danger" data-method="DELETE">Delete</a> </p>

		<% end %>
	</ul>




</body>
</html>